# If you are looking where omp is configure it is in the bash.nix file in the parent folder
version = 3
final_space = true

[palette]
pink = "#ff4f9b"
red = "#f65866"
orange = "#fa9534"
yellow = "#efbd5d"
green = "#8bcd5b"
cyan = "#00b8b8"
blue = "#41a7fc"
purple = "#c75ae8"
white = "#829bcd"
gray = "#68687a"
bg = "#242424"

[secondary_prompt]
template = '• '
foreground = 'p:green'

[[blocks]]
type = 'prompt'
alignment = 'left'
overflow = 'hide'

  [[blocks.segments]]
  leading_diamond = ''
  trailing_diamond = ' '
  foreground = 'p:bg'
  background = 'p:cyan'
  type = 'nix-shell'
  style = 'diamond'
  template = '{{ if ne .Type "unknown" }}nix{{ end }}'

  [[blocks.segments]]
  leading_diamond = ''
  trailing_diamond = ' '
  foreground = 'p:green'
  background = 'p:bg'
  type = 'path'
  style = 'diamond'

    [blocks.segments.properties]
    cache_duration = 'none'
    cycle = ['p:yellow', 'p:green', 'p:blue', 'p:purple']
    folder_format = ' %s'
    folder_icon = '...'
    folder_separator_icon = '  '
    max_depth = 2
    style = 'agnoster_short'

      [blocks.segments.properties.mapped_locations]
      'D:\OneDrive\Desktop\Code' = ''
      'D:\config' = ''
      'D:\config\nvim' = ''

  [[blocks.segments]]
  leading_diamond = ''
  trailing_diamond = ' '
  template = '{{ .RepoName }} at {{ .HEAD }}'
  foreground = 'p:bg'
  background = 'p:orange'
  type = 'git'
  style = 'diamond'

    [blocks.segments.properties]
    cache_duration = 'none'

  [[blocks.segments]]
  leading_diamond = ''
  trailing_diamond = ' '
  template = '{{ if ge .Working.Added 1 }}+{{ .Working.Added }}{{ end }}'
  foreground = 'p:green'
  background = 'p:bg'
  type = 'git'
  style = 'diamond'

    [blocks.segments.properties]
    fetch_status = true
    cache_duration = 'none'

  [[blocks.segments]]
  leading_diamond = ''
  trailing_diamond = ' '
  template = '{{ if ge .Working.Deleted 1 }}-{{ .Working.Deleted }}{{ end }}'
  foreground = 'p:red'
  background = 'p:bg'
  type = 'git'
  style = 'diamond'

    [blocks.segments.properties]
    fetch_status = true
    cache_duration = 'none'

  [[blocks.segments]]
  leading_diamond = ''
  trailing_diamond = ' '
  template = '{{ if ge .Working.Modified 1 }}~{{ .Working.Modified }}{{ end }}'
  foreground = 'p:yellow'
  background = 'p:bg'
  type = 'git'
  style = 'diamond'

    [blocks.segments.properties]
    fetch_status = true
    cache_duration = 'none'

  [[blocks.segments]]
  leading_diamond = ''
  trailing_diamond = ' '
  template = '{{ if ge .Working.Untracked 1 }}?{{ .Working.Untracked }}{{ end }}'
  foreground = 'p:purple'
  background = 'p:bg'
  type = 'git'
  style = 'diamond'

    [blocks.segments.properties]
    fetch_status = true
    cache_duration = 'none'

  [[blocks.segments]]
  leading_diamond = ''
  trailing_diamond = ' '
  foreground = 'p:bg'
  background = 'p:yellow'
  type = 'executiontime'
  style = 'diamond'

    [blocks.segments.properties]
    cache_duration = 'none'


[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

  [[blocks.segments]]
  template = ''
  type = 'text'
  style = 'plain'
  foreground_templates = ['{{ if ne .Code 0 }}p:red{{ end }}', 'p:blue']

    [blocks.segments.properties]
    cache_duration = 'none'
